// Generated by gencpp from file multiwii/SendMSPRawMessageRequest.msg
// DO NOT EDIT!


#ifndef MULTIWII_MESSAGE_SENDMSPRAWMESSAGEREQUEST_H
#define MULTIWII_MESSAGE_SENDMSPRAWMESSAGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <multiwii/MSPRawMessage.h>

namespace multiwii
{
template <class ContainerAllocator>
struct SendMSPRawMessageRequest_
{
  typedef SendMSPRawMessageRequest_<ContainerAllocator> Type;

  SendMSPRawMessageRequest_()
    : msg()  {
    }
  SendMSPRawMessageRequest_(const ContainerAllocator& _alloc)
    : msg(_alloc)  {
  (void)_alloc;
    }



   typedef  ::multiwii::MSPRawMessage_<ContainerAllocator>  _msg_type;
  _msg_type msg;




  typedef boost::shared_ptr< ::multiwii::SendMSPRawMessageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multiwii::SendMSPRawMessageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SendMSPRawMessageRequest_

typedef ::multiwii::SendMSPRawMessageRequest_<std::allocator<void> > SendMSPRawMessageRequest;

typedef boost::shared_ptr< ::multiwii::SendMSPRawMessageRequest > SendMSPRawMessageRequestPtr;
typedef boost::shared_ptr< ::multiwii::SendMSPRawMessageRequest const> SendMSPRawMessageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multiwii::SendMSPRawMessageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multiwii::SendMSPRawMessageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace multiwii

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'multiwii': ['/home/pi/propelled_cow/src/ros-multiwii/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::multiwii::SendMSPRawMessageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multiwii::SendMSPRawMessageRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multiwii::SendMSPRawMessageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multiwii::SendMSPRawMessageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiwii::SendMSPRawMessageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiwii::SendMSPRawMessageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multiwii::SendMSPRawMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e01cb4af5047b763cb98e1ac7628835";
  }

  static const char* value(const ::multiwii::SendMSPRawMessageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e01cb4af5047b76ULL;
  static const uint64_t static_value2 = 0x3cb98e1ac7628835ULL;
};

template<class ContainerAllocator>
struct DataType< ::multiwii::SendMSPRawMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multiwii/SendMSPRawMessageRequest";
  }

  static const char* value(const ::multiwii::SendMSPRawMessageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multiwii::SendMSPRawMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MSPRawMessage msg\n\
\n\
================================================================================\n\
MSG: multiwii/MSPRawMessage\n\
uint8 id\n\
uint8[] data\n\
";
  }

  static const char* value(const ::multiwii::SendMSPRawMessageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multiwii::SendMSPRawMessageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendMSPRawMessageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multiwii::SendMSPRawMessageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multiwii::SendMSPRawMessageRequest_<ContainerAllocator>& v)
  {
    s << indent << "msg: ";
    s << std::endl;
    Printer< ::multiwii::MSPRawMessage_<ContainerAllocator> >::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTIWII_MESSAGE_SENDMSPRAWMESSAGEREQUEST_H
