#!/usr/bin/env python

import rospy
from std_msgs.msg import Int16, Int32
from statistics import median

readings_cut = [0, 0, 0]
last_published = 0
offset = rospy.get_param('filter/offset')

# RATE = rospy.get_param('ultrasonic/rate')
pub = rospy.Publisher('ultrasonic_distance', Int16, queue_size=2)

def start():
	rospy.init_node('process_ultrasonic', anonymous=True)
	rospy.Subscriber('ultrasonic_raw', Int16, process_ultrasonic)
	rospy.spin()

def process_ultrasonic(data):
	global alpha
	global last_published
	
	dist_curr = data.data

	# delete the oldest value
	pop = readings_cut.pop(0)

	# update the list with the new cut reading
	readings_cut.append(dist_curr)

	# apply median filter to cut off extreme values
	median_value = median(readings_cut)

	# publish
	pub.publish(median_value)

	# save published value for the exponential filter
	last_published = median_value


def cut_crazy_values(data, new_reading):
	"""
    If the difference between current and previous value is larger than offset,
    the previous one. If the previous value was replaced, it returns the current value.
    """
	previous_reading = data[-1]
	if (abs(new_reading - previous_reading)) > offset:
		if previous_changed == False:
			previous_changed = True
			return previous_reading
		else:
			previous_changed = False
			return new_reading
	return new_reading

if __name__ == '__main__':
	start()