#!/usr/bin/env python

import rospy
import time
from std_msgs.msg import Int16, Int32

from propelled_cow.pwm_pigpio import PWM

servo_setting = rospy.get_param('servo')
pwm = PWM(servo_setting['pin'], servo_setting['min'], servo_setting['max'])
pwm.set_angle(170) # close the grabber

def callback(data):
	angle = data.data
	pwm.set_angle(angle)

def shutdown_servo():
	pwm.set_angle(50)
	time.sleep(1)
	pwm.stop()
	time.sleep(1)

def listener():
	rospy.init_node('servo_driver', anonymous=True)
	rospy.on_shutdown(shutdown_servo)
	rospy.Subscriber('servo_angle', Int16, callback)
	# spin() simply keeps python from exiting until this node is stopped
	rospy.spin()

if __name__ == '__main__':
	listener()