# PINS - GPIO.BOARD setting
# https://pinout.xyz/
# PWM - 4 pins, but only 2 identical outputs: GPIO 33 & 35 the same, GPIO 12 & 32 the same
#################################################
ultrasonic/trigger: 12
ultrasonic/echo: 18
throttle: 4
servo/pin: 17

# TOPIC RATES [Hz]
#################################################
ultrasonic/rate: 10 # max 33 Hz allowing to read max distance of 10 m
accelerometer_compass/rate: 200

# PID
#################################################
distance/Kp: 0.5
distance/Ki: 0
distance/Kd: 0.1

velocity/Kp: 0.5
velocity/Ki: 0
velocity/Kd: 0.1
velocity/demand: 20 # mm/s

# LIMITS / CONSTANTS
#################################################
distance_treshold: 800 # mm
filter/offset: 200 # mm

# min & max length of duty cycle for throttle, used in PID saturation
PWM/min: 500 # us
PWM/max: 1500 # us
servo/min: 750 # us
servo/max: 2300 # us