# PINS
ultrasonic/trigger: 18
ultrasonic/echo: 24
throttle: 15

# TOPIC RATES [Hz]
ultrasonic/rate: 10 # max 33 Hz allowing to read max distance of 10 m
accelerometer_compass/rate: 200

# PID
distance/Kp: 0.5
distance/Ki: 0
distance/Kd: 0.1

velocity/Kp: 0.5
velocity/Ki: 0
velocity/Kd: 0.1
velocity/demand: 20 # mm/s

# OTHER
distance_treshold: 700 # mm

# min & max length of duty cycle for throttle, used in PID saturation
PWM/min: 10 # us
PWM/max: 2000 # us