#!/usr/bin/env python

import rospy
# from std_msgs.msg import Int16, Int32

from propelled_cow.pwm_pigpio import PWM

duty_cycle = 1000 # us

def shutdown_throttle():
	pwm.set_duty_cycle(1000)

pwm = PWM(rospy.get_param('throttle'))
pwm.set_duty_cycle(duty_cycle)
rospy.init_node('arming', anonymous=True)
rospy.on_shutdown(shutdown_throttle)

