#!/usr/bin/env python

import rospy
from std_msgs.msg import Int16, Int32

ultrasonic_readings = [0, 0]

RATE = rospy.get_param('ultrasonic/rate')
pub = rospy.Publisher('ultrasonic_velocity', Int32, queue_size=10)
rospy.init_node('process_ultrasonic', anonymous=True)



def listener():
	rospy.Subscriber('ultrasonic_raw', Int16, velocity_pub)
	rospy.spin()

def velocity_pub(data):
	dist_curr = data.data
	ultrasonic_readings.append(dist_curr) # append current distance reading
	pop = ultrasonic_readings.pop(0) # remove the oldes value
	velocity = int((dist_curr - ultrasonic_readings[-2])*RATE) # mm/s
	pub.publish(velocity)

if __name__ == '__main__':
    listener()
