#!/usr/bin/env python

import rospy
from std_msgs.msg import Int16, Int32

from propelled_cow.pwm_pigpio import PWM

servo_setting = rospy.get_param('servo')
pwm = PWM(servo_setting['pin'], servo_setting['min'], servo_setting['max'])

def callback(data):
	angle = data.data
	servo.set_angle(angle)

def listener():
	rospy.init_node('servo_driver', anonymous=True)
	rospy.Subscriber('servo_angle', Int16, callback)
	# spin() simply keeps python from exiting until this node is stopped
	rospy.spin()

if __name__ == '__main__':
	listener()