#!/usr/bin/env python

import rospy
from std_msgs.msg import Int16, Int32

from propelled_cow.pwm_pigpio import PWM

pwm = PWM(rospy.get_param('throttle'))

def callback(data):
	duty_cycle = data.data
	pwm.set_duty_cycle(duty_cycle)

def listener():
	#run function before shutdown to reset throttle duty cycle
	rospy.on_shutdown(shutdown_throttle)

	rospy.init_node('throttle_driver', anonymous=True)
	rospy.Subscriber('PWM_throttle', Int16, callback)

	# spin() simply keeps python from exiting until this node is stopped
	rospy.spin()

def shutdown_throttle():
	pwm.set_duty_cycle(1000)

if __name__ == '__main__':
	listener()